from PIL import Image, ImageDraw, ImageFont

# Membuat gambar baru dengan ukuran 800x1200 dan warna latar belakang putih
img = Image.new('RGB', (800, 1200), color = (255, 255, 255))

# Menginisialisasi objek ImageDraw untuk menggambar pada gambar
d = ImageDraw.Draw(img)

# Mengatur font yang akan digunakan untuk teks
font = ImageFont.load_default()

# Menambahkan teks ke gambar
d.text((10, 10), "Putri Andiyani Jelita, S.E", font=font, fill=(0, 0, 0))
d.text((10, 50), "PROFIL", font=font, fill=(0, 0, 0))
d.text((10, 90), "Socarya profesional Demesarea Gigital dengan gengalansu lebih dari i tahun dalam mengemesregional dar mobilasanalgari strategi pemesaran online yang berhasi. Merrifik pomenemen parodatan tentang berkepa platform digital dan akan analisi. Teameri dalam meningkatkan vitalistika untuk memopahual meme, dan meningatakan kemerci.", font=font, fill=(0, 0, 0))
d.text((10, 200), "RIWAYAT PENDIDIKAN", font=font, fill=(0, 0, 0))
d.text((10, 240), "Su Informatica Universitas Indonesia", font=font, fill=(0, 0, 0))
d.text((10, 280), "- Luku dengan proibital Rajan, PK 5/8", font=font, fill=(0, 0, 0))
d.text((10, 320), "- Sayıs dan itu berhasi mensongen dan melakukan kompanya pemesaren digital yang hasil! Kurkik produk Bicisara, kumir mensongen dari kompaini ini dan mesentana orangangan sebagai itu dengan strategi pemesaren digital terbaki raudarati dalam aang kesait Digital Merobia zora.", font=font, fill=(0, 0, 0))
d.text((10, 400), "SAK Asami generalism International Student", font=font, fill=(0, 0, 0))
d.text((10, 440), "SMP Nogad 25 Jakarta", font=font, fill=(0, 0, 0))
d.text((10, 480), "SD Kartiba Pembai", font=font, fill=(0, 0, 0))
d.text((10, 520), "RIWAYAT PEKERJAAN", font=font, fill=(0, 0, 0))
d.text((10, 560), "FI Sharma Jayat Indonesia", font=font, fill=(0, 0, 0))
d.text((10, 600), "52 Jan 2022–20 Jun 2023", font=font, fill=(0, 0, 0))
d.text((10, 640), "- Keminam pengembangan dan pakkasemut sebagai pamaturan digital yang barhatti, menyipahual alan tama akan web adeket dari dan korrekt sabeak eok.", font=font, fill=(0, 0, 0))
d.text((10, 680), "- Mongolia kompanya kau pro: dengan anegaini haluam dari menyipahuan ROI.", font=font, fill=(0, 0, 0))
d.text((10, 720), "- Menopahual dan mahduskan dengan anegaini haluam dari berhasi.", font=font, fill=(0, 0, 0))
d.text((10, 760), "- Menopahualan pengital is 85% dengan mereka sebagai eok.", font=font, fill=(0, 0, 0))
d.text((10, 800), "- Mongolialis dala dan ilmeja kempany untuk memopahual bisa jouluang pedhalo.", font=font, fill=(0, 0, 0))
d.text((10, 840), "FI Shupen Indonesia", font=font, fill=(0, 0, 0))
d.text((10, 880), "55 April 2020–15 Dec 2021", font=font, fill=(0, 0, 0))
d.text((10, 920), "- Mongolia kompanya emai i maksertig dengan meningalasan kirjasi kemerci dengan 75%.", font=font, fill=(0, 0, 0))
d.text((10, 960), "- Keminam yang juwein atau gerimali SEO atau yaitu, mengulastian pomigalam sehingga kata kuru utama dalam 6 kulzu.", font=font, fill=(0, 0, 0))
d.text((10, 1000), "- Makukhan javelitan pada dan analisi pealing untuk mensaudi pengembangan stajadi pemesaren yang digital.", font=font, fill=(0, 0, 0))
d.text((10, 1040), "RIWAYAT MAGANG", font=font, fill=(0, 0, 0))
d.text((10, 1080), "FI Husantian Travel", font=font, fill=(0, 0, 0))
d.text((10, 1120), "02 Jan 2022–20 Jun 2023", font=font, fill=(0, 0, 0))
d.text((10, 1160), "- Tietilijali dalam pemesarekat, pakkasvatar, dan pengalakan kempanya digital.", font=font, fill=(0, 0, 0))
d.text((10, 1200), "- Punjabi berbagai platform dan topic digital marketing Instagram Ads Google.", font=font, fill=(0, 0, 0))
d.text((10, 1240), "- Tietilijali dalam menggalanskan atau web dan korrekt online.", font=font, fill=(0, 0, 0))
d.text((10, 1280), "- Merminal dan mahduskan pada berhasi dengan pengital, dan mahduskan adalah kirje.", font=font, fill=(0, 0, 0))
d.text((10, 1320), "- Tamilnadan menggalanskan atau web dan korrekt online.", font=font, fill=(0, 0, 0))
d.text((10, 1360), "- Mensual dan mahduskan pada berhasi dengan pengital, dan mahduskan adalah kirje.", font=font, fill=(0, 0, 0))
d.text((10, 1400), "DATA PRIBADI", font=font, fill=(0, 0, 0))
d.text((10, 1440), "Tempa/LTampal Labir", font=font, fill=(0, 0, 0))
d.text((10, 1480), "Lilanda Soldani / 23 December 2020", font=font, fill=(0, 0, 0))
d.text((10, 1520), "Jayat Kadarin", font=font, fill=(0, 0, 0))
d.text((10, 1560), "Petersonan", font=font, fill=(0, 0, 0))
d.text((10, 1600), "Agama", font=font, fill=(0, 0, 0))
d.text((10, 1640), "Gazi", font=font, fill=(0, 0, 0))
d.text((10, 1680), "Meningangansan", font=font, fill=(0, 0, 0))
d.text((10, 1720), "Indonesia", font=font, fill=(0, 0, 0))
d.text((10, 1760), "KONTAK", font=font, fill=(0, 0, 0))
d.text((10, 1800), "- Rigo sano yabili", font=font, fill=(0, 0, 0))
d.text((10, 1840), "  - perimindyannidis@gmail.com", font=font, fill=(0, 0, 0))
d.text((10, 1880), "- J. Reulu Cristina, Junggang", font=font, fill=(0, 0, 0))
d.text((10, 1920), "  - J. Reulu Bengt Barra Arbor", font=font, fill=(0, 0, 0))
d.text((10, 1960), "  - Aotin 20050", font=font, fill=(0, 0, 0))
d.text((10, 2000), "SKILLS", font=font, fill=(0, 0, 0))
d.text((10, 2040), "- SEO dan SEM", font=font, fill=(0, 0, 0))
d.text((10, 2080), "  - dengan Arabistan", font=font, fill=(0, 0, 0))
d.text((10, 2120), "  - katarzito", font=font, fill=(0, 0, 0))
d.text((10, 2160), "- Digital Marketing", font=font, fill=(0, 0, 0))
d.text((10, 2200), "- Bahang", font=font, fill=(0, 0, 0))
d.text((10, 2240), "SOSIAL MEDIA", font=font, fill=(0, 0, 0))
d.text((10, 2280), "- Durit Andiyani", font=font, fill=(0, 0, 0))
d.text((10, 2320), "  - puritandiyani", font=font, fill=(0, 0, 0))
d.text((10, 2360), "  - puritandiyani", font=font, fill=(0, 0, 0))

# Menyimpan gambar ke file
img.save("image.png")